particle minecraft:totem_particle ~ ~ ~
particle minecraft:totem_particle ~ ~ ~
particle minecraft:totem_particle ~ ~ ~
particle minecraft:totem_particle ~ ~ ~
particle minecraft:totem_particle ~ ~ ~
particle minecraft:totem_particle ~ ~ ~
particle minecraft:totem_particle ~ ~ ~
particle minecraft:totem_particle ~ ~ ~
particle minecraft:totem_particle ~ ~ ~
particle minecraft:totem_particle ~ ~ ~
particle minecraft:totem_particle ~ ~ ~
particle minecraft:totem_particle ~ ~ ~
particle minecraft:totem_particle ~ ~ ~
particle minecraft:totem_particle ~ ~ ~
particle minecraft:totem_particle ~ ~ ~
particle minecraft:totem_particle ~ ~ ~
particle minecraft:totem_particle ~ ~ ~
particle minecraft:totem_particle ~ ~ ~
particle minecraft:totem_particle ~ ~ ~
particle minecraft:totem_particle ~ ~ ~
particle minecraft:totem_particle ~ ~ ~
particle minecraft:totem_particle ~ ~ ~
particle minecraft:totem_particle ~ ~ ~
particle minecraft:totem_particle ~ ~ ~
particle minecraft:totem_particle ~ ~ ~
particle minecraft:totem_particle ~ ~ ~
particle minecraft:totem_particle ~ ~ ~
particle minecraft:totem_particle ~ ~ ~
particle minecraft:totem_particle ~ ~ ~
particle minecraft:totem_particle ~ ~ ~
particle minecraft:totem_particle ~ ~ ~
particle minecraft:totem_particle ~ ~ ~
particle minecraft:totem_particle ~ ~ ~
particle minecraft:totem_particle ~ ~ ~
particle minecraft:totem_particle ~ ~ ~