# Block user from entering forest until they have talked to the forest explorer and started activity
title @s subtitle If you want to go into the forest, talk to the §6Forest Explorer
title @s title Woah, hold on one second...