# Clear an agent inventory, by replacing each slot with air.
# Needed due to bug involving clear not working with agents.

execute @p ~ ~ ~ replaceitem entity @c slot.inventory 0 air
execute @p ~ ~ ~ replaceitem entity @c slot.inventory 1 air
execute @p ~ ~ ~ replaceitem entity @c slot.inventory 2 air
execute @p ~ ~ ~ replaceitem entity @c slot.inventory 3 air
execute @p ~ ~ ~ replaceitem entity @c slot.inventory 4 air
execute @p ~ ~ ~ replaceitem entity @c slot.inventory 5 air
execute @p ~ ~ ~ replaceitem entity @c slot.inventory 6 air
execute @p ~ ~ ~ replaceitem entity @c slot.inventory 7 air
execute @p ~ ~ ~ replaceitem entity @c slot.inventory 8 air
execute @p ~ ~ ~ replaceitem entity @c slot.inventory 9 air
execute @p ~ ~ ~ replaceitem entity @c slot.inventory 10 air
execute @p ~ ~ ~ replaceitem entity @c slot.inventory 11 air
execute @p ~ ~ ~ replaceitem entity @c slot.inventory 12 air
execute @p ~ ~ ~ replaceitem entity @c slot.inventory 13 air
execute @p ~ ~ ~ replaceitem entity @c slot.inventory 14 air
execute @p ~ ~ ~ replaceitem entity @c slot.inventory 15 air
execute @p ~ ~ ~ replaceitem entity @c slot.inventory 16 air
execute @p ~ ~ ~ replaceitem entity @c slot.inventory 17 air
execute @p ~ ~ ~ replaceitem entity @c slot.inventory 18 air
execute @p ~ ~ ~ replaceitem entity @c slot.inventory 19 air
execute @p ~ ~ ~ replaceitem entity @c slot.inventory 20 air
execute @p ~ ~ ~ replaceitem entity @c slot.inventory 21 air
execute @p ~ ~ ~ replaceitem entity @c slot.inventory 22 air
execute @p ~ ~ ~ replaceitem entity @c slot.inventory 23 air
execute @p ~ ~ ~ replaceitem entity @c slot.inventory 24 air
execute @p ~ ~ ~ replaceitem entity @c slot.inventory 25 air
execute @p ~ ~ ~ replaceitem entity @c slot.inventory 26 air
